services:
  postgres:
    image: postgres:18-alpine
    container_name: todolist-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todolistdb
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: password
